NUMERIC_COLS = ['time_in_hospital',
                'num_lab_procedures',
                'num_procedures',
                'num_medications',
                'number_outpatient',
                'number_inpatient',
                'number_diagnoses']

ONEHOT_COLS = ['race',
               'gender',
               'admission_type_id',
               'admission_source_id',
               'discharge_disposition_id',
               'A1Cresult',
               'max_glu_serum',
               'insulin',
               'metformin',
               'weight',
               'payer_code',
               'medical_specialty']

ORINDAL_COLS = ['age']

ENGINEERED_COLS = ['missing_insulin',
                   'missing_metformin',
                   'metformin_change',
                   'insulin_change',
                   'missing_weight',
                   'payer_code_cleaned',
                   'missing_a1c',
                   'missing_max_glu_serum']

DROP_COLS = ['patient_nbr',
             'encounter_id',
             'target',
             'repaglinide',
             'nateglinide',
             'chlorpropamide',
             'glimepiride',
             'acetohexamide',
             'glipizide',
             'glyburide',
             'tolbutamide',
             'pioglitazone',
             'rosiglitazone',
             'acarbose',
             'miglitol',
             'troglitazone',
             'tolazamide',
             'examide',
             'citoglipton',
             'insulin',
             'glyburide.metformin',
             'glipizide.metformin',
             'glimepiride.pioglitazone',
             'metformin.rosiglitazone',
             'metformin.pioglitazone',
             'metformin',
             'insulin',
             'A1Cresult',
             'weight',
             'diag_1',
             'diag_2',
             'diag_3',
             'max_glu_serum',
             'change']

TARGET_COL = ['target']
